language: node_js
node_js:
    - "8"
addons: # Literally taken from puppeteer's TravisCI config: https://github.com/GoogleChrome/puppeteer
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
before_install:
    - npm install -g greenkeeper-lockfile@1
before_script:
    - greenkeeper-lockfile-update
after_script:
    - greenkeeper-lockfile-upload
    - npm run coverage-ci
