export default {
    REQUEST_USERS: 'REQUEST_USERS',
    RESOLVE_USERS: 'RESOLVE_USERS',
    REJECT_USERS: 'REJECT_USERS',

    REQUEST_USER: 'REQUEST_USER',
    RESOLVE_USER: 'RESOLVE_USER',
    REJECT_USER: 'REJECT_USER',

    REQUEST_ADD_USER: 'REQUEST_ADD_USER',
    RESOLVE_ADD_USER: 'RESOLVE_ADD_USER',
    REJECT_ADD_USER: 'REJECT_ADD_USER',

    REQUEST_UPDATE_USER: 'REQUEST_UPDATE_USER',
    RESOLVE_UPDATE_USER: 'RESOLVE_UPDATE_USER',
    REJECT_UPDATE_USER: 'REJECT_UPDATE_USER',

    REQUEST_DELETE_USER: 'REQUEST_DELETE_USER',
    RESOLVE_DELETE_USER: 'RESOLVE_DELETE_USER',
    REJECT_DELETE_USER: 'REJECT_DELETE_USER'
};